HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Controllers/ApartmentBookingController.cs
using HouseRentalManagementSystem.IRepository;
using HouseRentalManagementSystem.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace HouseRentalManagementSystem.Areas.User.Controllers
{
    [Authorize]
    public class ApartmentBookingController : Controller
    {
        private readonly IApartmentBookingRepository iApartmentBookingRepository;
        private readonly IApartmentRepository iApartmentRepository;
        private readonly IBuildingRepository iBuildingRepository;
        private readonly ITenantRepository iTenantRepository;
        private readonly IBookingStatusRepository iBookingStatusRepository;
        private readonly IPaymentTypeRepository iPaymentTypeRepository;
        private readonly ISecurityDepositRepository iSecurityDepositRepository;
        private readonly IBookingPaymentRepository iBookingPaymentRepository;
        private readonly IViewUnitStatusRepository iViewUnitStatusRepository;
        public ApartmentBookingController(IApartmentBookingRepository _iApartmentBookingRepository, IApartmentRepository _iApartmentRepository, IBuildingRepository _iBuildingRepository, ITenantRepository _iTenantRepository, IBookingStatusRepository _iBookingStatusRepository, IPaymentTypeRepository _iPaymentTypeRepository,
            ISecurityDepositRepository _iSecurityDepositRepository, IBookingPaymentRepository _iBookingPaymentRepository, IViewUnitStatusRepository _iViewUnitStatusRepository)
        {
            iApartmentBookingRepository = _iApartmentBookingRepository;
            iApartmentRepository = _iApartmentRepository;
            iBuildingRepository = _iBuildingRepository;
            iTenantRepository = _iTenantRepository;
            iBookingStatusRepository = _iBookingStatusRepository;
            iPaymentTypeRepository = _iPaymentTypeRepository;
            iSecurityDepositRepository = _iSecurityDepositRepository;
            iBookingPaymentRepository = _iBookingPaymentRepository;
            iViewUnitStatusRepository = _iViewUnitStatusRepository;
        }
        public IActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            //ViewBag.Buildings = iBuildingRepository.GetAll();
            //ViewBag.Apartments = iApartmentRepository.GetAll();
            //ViewBag.Tenants = iTenantRepository.GetAll();
            //ViewBag.BookingStatuses = iBookingStatusRepository.GetAll();
            IEnumerable<ApartmentBookingViewModel> itemList = iApartmentBookingRepository.GetAll();
            int indexNumber = 0;
            foreach (var item in itemList)
            {
                item.SirialNumber = indexNumber += 1;

            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                itemList = itemList.Where(e => e.BookingStartDate.ToString().Contains(SearchString.ToString())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    itemList = itemList.OrderByDescending(e => e.SirialNumber).ToList();
                    break;
                default:
                    itemList = itemList.OrderBy(e => e.SirialNumber).ToList();
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(itemList.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public PartialViewResult Create()
        {
            ViewBag.Details = "Show";
            ViewBag.Buildings = iBuildingRepository.GetAll();
            ViewBag.Apartments = iApartmentRepository.GetAll();
            ViewBag.Tenants = iTenantRepository.GetAll();
            ViewBag.BookingStatuses = iBookingStatusRepository.GetAll();
            ApartmentBookingViewModel obj = new ApartmentBookingViewModel();
            return PartialView("~/Areas/User/Views/ApartmentBooking/_Create.cshtml", obj);
        }
        [HttpPost]
        public IActionResult Create(ApartmentBookingViewModel objModel)
        {
            bool result = false;
            if (objModel.PaymentTypeId > 0)
            {
                if (ModelState.IsValid)
                {
                    objModel.BookingStatusCode = 1;
                    ApartmentBookingViewModel returnObj = iApartmentBookingRepository.Insert(objModel);
                    if (returnObj.AptBookingId>0)
                    {
                        ViewUnitStatusViewModel objUnitStatus = new ViewUnitStatusViewModel
                        {
                            AptBookingId = returnObj.AptBookingId,
                            AptId=objModel.AptId,
                            StatusDate = DateTime.Now,
                            AvailableYn="NO",
                        };
                        BookingPaymentViewModel objPayment = new BookingPaymentViewModel
                        {
                            PaymentTypeId = objModel.PaymentTypeId,
                            PaymentDate = objModel.PaymentDate,
                            PaymemtAmount=objModel.PaymemtAmount,
                            AptBookingId=returnObj.AptBookingId,
                        };
                        SecurityDepositViewModel objDeposit = new SecurityDepositViewModel
                        {
                            ReturnDate = objModel.ReturnDate,
                            DepositAmount = objModel.SecurityDepositAmount,
                            AptBookingId= returnObj.AptBookingId,
                        };
                        iViewUnitStatusRepository.Insert(objUnitStatus);
                        iBookingPaymentRepository.Insert(objPayment);
                        iSecurityDepositRepository.Insert(objDeposit);
                    }
                    result = true;

                }
            }
            else
            {
                ModelState.Remove("ReturnDate");
                ModelState.Remove("PaymentTypeId");
                ModelState.Remove("PaymentDate");
                if (ModelState.IsValid)
                {
                    objModel.BookingStatusCode = 2;
                    ApartmentBookingViewModel returnObj = iApartmentBookingRepository.Insert(objModel);
                    if (returnObj.AptBookingId > 0)
                    {
                        ViewUnitStatusViewModel objUnitStatus = new ViewUnitStatusViewModel
                        {
                            AptBookingId = returnObj.AptBookingId,
                            AptId = objModel.AptId,
                            StatusDate = DateTime.Now,
                            AvailableYn = "YES",
                        };
                        iViewUnitStatusRepository.Insert(objUnitStatus);
                    }
                    result = true;
                }
            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Booking is not save";
                return RedirectToAction("Message", "Error", new { area = "" });
            }
        }
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            ViewBag.Details = "Show";
            ViewBag.Buildings = iBuildingRepository.GetAll();
            ViewBag.Tenants = iTenantRepository.GetAll();
            ViewBag.BookingStatuses = iBookingStatusRepository.GetAll();
            ViewBag.PaymentTypes = iPaymentTypeRepository.GetAll();
            ApartmentBookingViewModel booking = iApartmentBookingRepository.GetById(id);
            ViewBag.Apartments = iApartmentRepository.GetByBuildingId(booking.BuildingId);
            return PartialView("~/Areas/User/Views/ApartmentBooking/_Edit.cshtml", booking);
        }
        [HttpPost]
        public IActionResult Edit(ApartmentBookingViewModel objModel)
        {
            bool result = false;
            if (objModel.AptBookingId>0)
            {
                if (objModel.PaymentTypeId > 0)
                {
                    ModelState.Remove("ReturnDate");
                    ModelState.Remove("PaymentTypeId");
                    ModelState.Remove("PaymentDate");
                    if (ModelState.IsValid)
                    {
                        objModel.BookingStatusCode = 1;
                        ApartmentBookingViewModel returnObj = iApartmentBookingRepository.Update(objModel);
                        if (returnObj.AptBookingId > 0)
                        {
                            ViewUnitStatusViewModel returnViewUnitStatusObj = iViewUnitStatusRepository.GetViewUnitStatusByBookingId(returnObj.AptBookingId);
                            if (returnViewUnitStatusObj != null)
                            {
                                ViewUnitStatusViewModel objUnitStatus = new ViewUnitStatusViewModel
                                {
                                    StatusId = returnViewUnitStatusObj.StatusId,
                                    AptBookingId = returnObj.AptBookingId,
                                    AptId = objModel.AptId,
                                    StatusDate = DateTime.Now,
                                    AvailableYn = "NO",
                                };
                                iViewUnitStatusRepository.Update(objUnitStatus);
                            }
                            else
                            {
                                ViewUnitStatusViewModel objUnitStatus = new ViewUnitStatusViewModel

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/ApartmentBooking/Index.cshtml
@model IEnumerable<ApartmentBookingViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div class="pl-0">
        <div><span class="page_header">Apartment Booking</span></div>
        <div style="padding-left:0">
            <button type="button" class="btn_add_new" data-bs-toggle="modal" data-bs-target="#CreateModal" onclick='Create()'>Create New</button>
        </div>
    </div>
    <table class="table table-bordered table-striped list_table">
        <thead>
            <tr>
                <th class="text-center">
                    @Html.ActionLink("###", "Index", new { SortOrder = ViewBag.SortNameParam }, new { @class = "text-decoration-none text-white" })
                </th>
                <th>
                    Building Name
                </th>
                <th class="text-center">
                    Apartment Name
                </th>
                <th class="text-center">
                    Tenant Name
                </th>
                <th>
                    Booking Status
                </th>
                <th class="text-center">
                    Booking Start Date
                </th>
                <th class="text-center">
                    Booking End Date
                </th>
                <th class="text-center">
                    Other Details
                </th>
                <th class="text-center tbl_action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @item.SirialNumber
                    </td>
                    <td>
                        @item.BuildingShortName
                    </td>
                    <td>
                        @item.ApartmentName
                    </td>
                    <td>
                        @item.TenantFullName
                    </td>
                    <td>
                        @item.BookingStatusDescription
                    </td>
                    <td>
                        @item.BookingStartDate.ToShortDateString()
                    </td>
                    <td class="text-center">
                        @item.BookingEndDate.ToShortDateString()
                    </td>
                    <td class="tbl_large_field">
                        @item.OtherBookingDetails
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <div class="dropdown">
                                <a class="btn_table dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" onclick='Update(@item.AptBookingId)' data-bs-toggle="modal" data-bs-target="#EditModal">Edit</a></li>
                                    <li><a class="dropdown-item" asp-area="User" asp-controller="ApartmentBooking" asp-action="Delete" asp-route-id="@item.AptBookingId" onclick="return confirm('Are you sure to delete?')">Delete</a></li>
                                    <li><a class="dropdown-item" onclick='Details(@item.AptBookingId)' data-bs-toggle="modal" data-bs-target="#DetailsModal">Details</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div class="search_section">
        <form asp-action="Index" method="get">
            <div>
                <span class="search_title">Find By Tenant Name: </span>
                <input type="text" class="input_search" name="SearchString" value="@ViewBag.CurrentFilter" />
                <input type="submit" value="Search" class="btn_search" />
                <a asp-action="Index" class="btn_back_to_list">Back to List</a>
            </div>
        </form>
    </div>
    <div class="page_section">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navication" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
    </div>
</div>
<div class="modal fade" id="CreateModal" tabindex="-1" aria-labelledby="CreateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Create Apartment</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="CreateDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/ApartmentBooking/_Create.cshtml" />
                        //@await Html.PartialAsync("_Create", new ApartmentBookingViewModel())
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="EditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Update Tenant</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="EditDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/ApartmentBooking/_Edit.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DetailsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5 ba">
                <h3 class="modal-title" id="detailsModalLabel">Tenant Details</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="DetailsDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/ApartmentBooking/_Details.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function Create() {
        $.ajax({
            url: "/User/ApartmentBooking/Create",
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#CreateDiv').show();
                $('#CreateDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }
    function Update(id) {
        $.ajax({
            url: "/User/ApartmentBooking/Edit?id=" + id,
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#EditDiv').show();
                $('#EditDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }
    function Details(id) {
        $.ajax({
            url: "/User/ApartmentBooking/Details?id=" + id,
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#DetailsDiv').show();
                $('#DetailsDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }
</script>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/ApartmentBooking/_Create.cshtml
@model ApartmentBookingViewModel
<form enctype="multipart/form-data" asp-action="Create" method="post" id="form">
    <div class="col-md-12 mx-auto d-flex">
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="BuildingShortName" class="form-label"></label>
                <select asp-for="BuildingId" class="form-control" asp-items="@(new SelectList(string.Empty, "BuildingId", "BuildingShortName" ))">
                    <option value="" class="text-danger">Select...</option>
                </select>
                <span asp-validation-for="BuildingId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="ApartmentName" class="form-label"></label>
                @if (ViewBag.Apartments != null)
                {
                    <select asp-for="AptId" class="form-control" asp-items='@(new SelectList(string.Empty, "AptId", "ApartmentName" ))'>
                    </select>
                }
                <span asp-validation-for="AptId" class="text-danger"></span>
            </div>

            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="MonthlyRent" class="form-label"></label>
                <input asp-for="MonthlyRent" class="form-control" value=""  readonly/>
                <span asp-validation-for="MonthlyRent" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="SecurityDepositAmount" class="form-label"></label>
                <input asp-for="SecurityDepositAmount" class="form-control" value="" readonly/>
                <span asp-validation-for="SecurityDepositAmount" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="TenantFullName" class="form-label"></label>
                @if (ViewBag.Tenants != null)
                {
                    <select asp-for="TenantId" class="form-control" asp-items='@(new SelectList(@ViewBag.Tenants, "TenantId", "TenantFullName" ))'>
                        <option value="" class="text-danger">Select...</option>
                    </select>
                }
                <span asp-validation-for="TenantId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="BookingStartDate" class="form-label"></label>
                <input asp-for="BookingStartDate" class="form-control" value="" />
                <span asp-validation-for="BookingStartDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="BookingEndDate" class="form-label"></label>
                <input asp-for="BookingEndDate" class="form-control" value="" />
                <span asp-validation-for="BookingEndDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 px-3 col-md-12 float-left">
                <label asp-for="OtherBookingDetails" class="form-label d-block"></label>
                <textarea asp-for="OtherBookingDetails" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)"></textarea>
                <span asp-validation-for="OtherBookingDetails" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-12 mx-auto d-flex">
        <div id="paymentSection" class="dis-none row">
            <div><span class="sub_page_header float-none">PAYMENT SECTION</span></div><br />
            <div class="form-group mb-3 col-md-6 float-left px-3">
                <label asp-for="PaymentTypeDetails" class="form-label"></label>
                <select asp-for="PaymentTypeId" class="form-control" asp-items="@(new SelectList(string.Empty, "PaymentTypeId", "PaymentTypeDetails" ))">
                </select>
                <span asp-validation-for="PaymentTypeId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 px-3 col-md-6 float-left">
                <label asp-for="PaymentDate" class="form-label d-block"></label>
                <input asp-for="PaymentDate" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-dd")" readonly/>
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 px-3 col-md-6 float-left">
                <label asp-for="ReturnDate" class="form-label d-block"></label>
                <input asp-for="ReturnDate" class="form-control" value="" readonly/>
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3 px-3 col-md-6 float-left">
                <label asp-for="PaymemtAmount" class="form-label"></label>
                <input type="text" asp-for="PaymemtAmount" class="form-control" />
                <span asp-validation-for="PaymemtAmount" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-12 mx-auto d-flex">
        <div class="row">
            <div class="form-group mb-3 col-md-12 px-3">
                <input type="button" value="Confirmed" id="btnConfirmed" class="btn btn_modal_close" />
                <input type="submit" value="Provisional" id="btnProvisional" class="btn btn_modal" />


                <input type="button" value="Cencel" id="btnCancelPayment" class="btn btn_modal_close dis-none" />
                <input type="submit" value="Submit" id="btnSubmit" class="btn btn_modal dis-none" />
            </div>
        </div>
    </div>
</form>
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script>
    $(function () {
        $.ajax({
            type: "GET",
            url: "/User/ApartmentBooking/GetBuilding/",
            dataType: "Json",
            success: function (data) {
                $.each(data, function (index, value) {
                    $('#BuildingId').append('<option value="' + value.buildingId + '">' + value.buildingShortName + '</option>')
                });
            }
        });
        $('#BuildingId').change(function () {
            $('#AptId').empty();
            var id = $('#BuildingId').val();
            if (id > 0) {
                $.ajax({
                    type: "POST",
                    url: "/User/ApartmentBooking/GetByBuildingId?id=" + id,
                    dataType: "Json",
                    success: function (data) {
                        $('#AptId').append('<option class="text-danger" value="">Select...</option>')
                        $.each(data, function (index, value) {
                            $('#AptId').append('<option value="' + value.aptId + '">' + value.apartmentName + '</option>')
                        });
                    }
                })
            }
        });
        $('#AptId').change(function () {
            $('#MonthlyRent').empty();
            $('#SecurityDepositAmount').empty();
            var id = $('#AptId').val();
            if (id > 0) {
                $.ajax({
                    type: "POST",
                    url: "/User/ApartmentBooking/GetByApartmentId?id=" + id,
                    dataType: "Json",
                    success: function (data) {
                        $("#MonthlyRent").attr("value", data.monthlyRent);
                        $("#SecurityDepositAmount").attr("value", data.securityDepositAmount);
                    }
                })
            }
        });
        $('#BookingEndDate').change(function () {
            var now = new Date($("#BookingEndDate").val());
            var day = ("0" + now.getDate()).slice(-2);
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            var today = now.getFullYear() + "-" + (month) + "-" + (day);
            $('#ReturnDate').val(today);
        });
        //$('#btnConfirmed').click(function () {
        //    var monthlyRent = parseInt($('#MonthlyRent').val());
        //    var dipositeAmount = parseInt($('#SecurityDepositAmount').val());
        //    $("#PaymemtAmount").val(monthlyRent + dipositeAmount);
        //});

    });

    //    $('#Quantity').focusout(function () {
    //    var quantity = parseInt($('#Quantity').val());
    //    var availableQuantity = parseInt($('#AvailableQuantity').val());
    //    var salesUnitPrice = parseInt($('#SalesUnitPrice').val());
    //    if (availableQuantity < quantity) {
    //        alert("You Do not enough Product");
    //    $('#Quantity').val(0);
    //    $("#TotalPrice").val(0);
    //    return false;
    //    }
    //    else {
    //        $("#TotalPrice").val(quantity * salesUnitPrice);
    //    return true;
    //    }

    //});
    //    $('#Quantity').keyup(function () {
    //    var quantity = parseInt($('#Quantity').val());
    //    var salesUnitPrice = parseInt($('#SalesUnitPrice').val());
    //    $("#TotalPrice").val(quantity * salesUnitPrice);
    //});
    //    $('#btnSave').click(function () {
    //    var quantity = parseInt($('#Quantity').val());
    //    var availableQuantity = parseInt($('#AvailableQuantity').val());
    //    var salesUnitPrice = parseInt($('#SalesUnitPrice').val());
    //    if (availableQuantity < quantity) {
    //        alert("You Do not enough Product");
    //    $('#Quantity').val(0);
    //    $("#TotalPrice").val(0);
    //    return false;
    //    }
    //    else {
    //        $("#TotalPrice").val(quantity * salesUnitPrice);
    //    return true;
    //    }

    //});
    $(document).ready(function () {
        $('#btnConfirmed').click(showPaymentSection);
        $('#btnCancelPayment').click(hidePaymentSection);
    })

    function showPaymentSection() {
        $("#form").valid();
        if ($("#form").valid()) {
            $('#paymentSection').fadeIn();
            $('#btnConfirmed').hide();
            $('#btnProvisional').hide();
            $('#btnSubmit').show();
            $('#btnCancelPayment').show();
            var now = new Date($("#BookingEndDate").val());
            var day = ("0" + now.getDate()).slice(-2);
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            var today = now.getFullYear() + "-" + (month) + "-" + (day);
            $('#ReturnDate').val(today);
            var monthlyRent = parseInt($('#MonthlyRent').val());
            var dipositeAmount = parseInt($('#SecurityDepositAmount').val());
            $("#PaymemtAmount").val(monthlyRent + dipositeAmount);
            $.ajax({
                type: "GET",
                url: "/User/ApartmentBooking/GetAllPaymentType/",
                dataType: "Json",
                success: function (data) {
                    $.each(data, function (index, value) {
                        $('#PaymentTypeId').append('<option class="text-danger" value="">Select...</option>')
                        $('#PaymentTypeId').append('<option value="' + value.paymentTypeId + '">' + value.paymentTypeDetails + '</option>')
                    });
                }
            });
        }
    }
    function hidePaymentSection() {
        $('#paymentSection').hide();
        $('#btnSubmit').hide();
        $('#btnCancelPayment').hide();
        $('#btnConfirmed').fadeIn();
        $('#btnProvisional').fadeIn();
        $('#PaymentTypeId').empty();
        $('#ReturnDate').val("");
        $('#PaymemtAmount').val();
    }

</script>