HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/Security/Controllers/RolesController.cs
using HouseRentalManagementSystem.Data;
using HouseRentalManagementSystem.Models;
using HouseRentalManagementSystem.SecurityViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HouseRentalManagementSystem.Areas.Security.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public RolesController(RoleManager<ApplicationRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (ModelState.IsValid)
            {
                if (roleName != null)
                {
                    await _roleManager.CreateAsync(new ApplicationRole(roleName.Trim()));
                }
                return RedirectToAction("Index");
            }
            return View("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"This {roleId} does not belong With any Role";
                return View("NotFound");
            }
            var model = new UserRolesViewModel
            {
                RoleId = role.Id,
                RoleName = role.Name,
                JsonData = role.JsonData
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserRolesViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"This {model.RoleId} does not belong With any Role";
                return View("Message");
            }
            else
            {
                if (role.Name != "Admin")
                {
                    role.Name = model.RoleName;
                    role.JsonData = role.JsonData;
                    var result = await _roleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        UserAndRoleDataInitializer.SeedData(_userManager, _roleManager);
                        return RedirectToAction("Index");
                    }
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }

                }
                else
                {
                    ViewBag.ErrorMessage = $"Admin Role can not be Edited";
                    return View("Message");
                }
            }
            return View(model);
        }
        public async Task<ActionResult> Delete(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role.Name!="Admin")
            {
                await _roleManager.DeleteAsync(role);
                return RedirectToAction("Index");
            }
            else
            {

                ViewBag.ErrorMessage = $"Admin Role can not be deleted";
                return View("Message");
            }
        }
    }
}

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/Security/Controllers/UsersController.cs
using HouseRentalManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HouseRentalManagementSystem.Areas.Security.Controllers
{
    
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IWebHostEnvironment iWebHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        public UsersController(UserManager<ApplicationUser> userManager, IWebHostEnvironment _iWebHostEnvironment)
        {
            _userManager = userManager;
            iWebHostEnvironment = _iWebHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }
        public async Task<ActionResult> Delete(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user.ImageName != null)
            {
                string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/user_images");
                DeleteExistingImage(Path.Combine(uploadFolder, user.ImageName));
            }
            if (user.UserName != "admin")
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        private void DeleteExistingImage(string imagePath)
        {
            FileInfo fileObj = new FileInfo(imagePath);
            if (fileObj.Exists)
            {
                fileObj.Delete();
            }
        }

    }
}

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Controllers/TenantController.cs
using HouseRentalManagementSystem.IRepository;
using HouseRentalManagementSystem.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace HouseRentalManagementSystem.Areas.User.Controllers
{
    [Authorize]
    public class TenantController : Controller
    {
        private readonly IWebHostEnvironment iWebHostEnvironment;
        private readonly ITenantRepository iTenantRepository;
        public TenantController(ITenantRepository _iTenantRepository, IWebHostEnvironment _iWebHostEnvironment)
        {
            iTenantRepository = _iTenantRepository;
            iWebHostEnvironment = _iWebHostEnvironment;
        }
        public IActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            IEnumerable<TenantViewModel> itemList = iTenantRepository.GetAll();
            int indexNumber = 0;
            foreach (var item in itemList)
            {
                item.SirialNumber = indexNumber += 1;
                if (Convert.ToInt16(item.GenderCode) == 0)
                {
                    item.GenderProperty = "Female";
                }
                else
                {
                    item.GenderProperty = "Male";
                }

            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                itemList = itemList.Where(e => e.TenantFullName.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    itemList = itemList.OrderByDescending(e => e.SirialNumber).ToList();
                    break;
                default:
                    itemList = itemList.OrderBy(e => e.SirialNumber).ToList();
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(itemList.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public IActionResult Create(TenantViewModel objModel)
        {
            string uniqueImageName = null;
            bool result = false;
            if (Convert.ToInt16(objModel.GenderCreate) == 0)
            {
                objModel.GenderCode = "0";
            }
            else
            {
                objModel.GenderCode = "1";
            }
            if (ModelState.IsValid)
            {
                if (objModel.Photo != null)
                {
                    string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/tenant_images");
                    string uploadFolder1 = Path.Combine(iWebHostEnvironment.WebRootPath, "images/tenant_images/");
                    uniqueImageName = Guid.NewGuid().ToString() + "_" + objModel.Photo.FileName;
                    string filePath = Path.Combine(uploadFolder, uniqueImageName);
                    FileStream fileStream = new FileStream(filePath, FileMode.Create);
                    objModel.Photo.CopyTo(fileStream);
                    fileStream.Close();
                    objModel.ImageFullPath = uploadFolder1 + uniqueImageName;
                    objModel.ImageName = uniqueImageName;
                }
                iTenantRepository.Insert(objModel);
                result = true;
            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message="Tenant is not save";
                return RedirectToAction("Message");
            }
        }
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            ViewBag.Details = "Show";
            TenantViewModel tenant = iTenantRepository.GetById(id);
            return PartialView("~/Areas/User/Views/Tenant/_Edit.cshtml", tenant);
        }
        [HttpPost]
        public IActionResult Edit(TenantViewModel objModel)
        {
            string uniqueImageName = null;
            bool result = false; 
            if (Convert.ToInt16(objModel.GenderCode) == 0)
            {
                objModel.GenderCode = "0";
            }
            else
            {
                objModel.GenderCode = "1";
            }
            if (ModelState.IsValid)
            {
                if (objModel.TenantId > 0)
                {
                    if (objModel.Photo != null)
                    {
                        string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/tenant_images");
                        string uploadFolder1 = Path.Combine(iWebHostEnvironment.WebRootPath, "images/tenant_images/");
                        DeleteExistingImage(Path.Combine(uploadFolder, objModel.ImageName));
                        uniqueImageName = Guid.NewGuid().ToString() + "_" + objModel.Photo.FileName;
                        string filePath = Path.Combine(uploadFolder, uniqueImageName);
                        FileStream fileStream = new FileStream(filePath, FileMode.Create);
                        objModel.Photo.CopyTo(fileStream);
                        fileStream.Close();
                        objModel.ImageFullPath = uploadFolder1 + uniqueImageName;
                        objModel.ImageName = uniqueImageName;
                    }
                    iTenantRepository.Update(objModel);
                    result = true;
                }
            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Tenant is not Edited";
                return RedirectToAction("Message");
            }
        }
        [HttpGet] 
        public IActionResult Details(int id)
        {
            ViewBag.Details = "Show";
            TenantViewModel tenant = iTenantRepository.GetById(id);
            if (Convert.ToInt16(tenant.GenderCode) == 0)
            {
                tenant.GenderProperty = "Female";
            }
            else
            {
                tenant.GenderProperty = "Male";
            }

            return PartialView("~/Areas/User/Views/Tenant/_Details.cshtml", tenant);
        }
        public IActionResult ShowImage(int id)
        {
            ViewBag.Details = "Show";
            TenantViewModel tenant = iTenantRepository.GetById(id);
            if (Convert.ToInt16(tenant.GenderCode) == 0)
            {
                tenant.GenderProperty = "Female";
            }
            else
            {
                tenant.GenderProperty = "Male";
            }

            return PartialView("~/Areas/User/Views/Tenant/_ShowImage.cshtml", tenant);
        }
        public IActionResult Delete(int id)
        {
            TenantViewModel obj = iTenantRepository.GetById(id);
            if (obj.ImageName != null)
            {
                string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/tenant_images");
                DeleteExistingImage(Path.Combine(uploadFolder, obj.ImageName));
            }
            iTenantRepository.Delete(obj.TenantId);
            return RedirectToAction("Index");
        }

        private void DeleteExistingImage(string imagePath)
        {
            FileInfo fileObj = new FileInfo(imagePath);
            if (fileObj.Exists)
            {
                fileObj.Delete();
            }
        }
    }

}

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Views/Shared/Message.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="text-warning">@ViewBag.ErrorMessage</h4>
<br />
<a asp-area="Common" asp-controller="Home" asp-action="Dashboard"><span>Back To Home</span></a>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Views/Shared/PaymentReport.cshtml
@model FastReport.Web.WebReport
@{
    ViewData["Title"] = "Tenants - Report";
}
<a class="btn btn-danger" asp-controller="Reports" asp-action="PdfPaymentReport">Download PDF</a><br /><br />
@await ViewBag.WebReport.Render()

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Views/Shared/Report.cshtml
@model FastReport.Web.WebReport
@{
    ViewData["Title"] = "Tenants - Report";
}
<a class="btn btn-danger" asp-controller="Reports" asp-action="Pdf">Download PDF</a><br /><br />
@await ViewBag.WebReport.Render()

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="">
    <meta name="author" content="Themepixels">

    <link rel="icon" type="image/png" href="~/images/app_images/favicon.png" />
    <title>DashNav - Dashboard Sidebar Navigation</title>


    <!--CSS Link-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="~/lib/remixicon/fonts/remixicon.css" rel="stylesheet">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/style.min.css">
    <link href="~/Custom/css/styles.css" rel="stylesheet" />



    <!--Jquery Link-->
    <script src="~/angular.js/angular.js"></script>
    <script src="~/danialfarid-angular-file-upload/ng-file-upload.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/feathericons/feather.min.js"></script>
    <script src="~/lib/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/script.js"></script>
    <script src="~/Custom/js/main.js"></script>

</head>
<body class="skin-base animate">

    @{ if (User.Identity.IsAuthenticated)
        {
            <div class="sidebar minimized">
                <div class="sidebar-header">
                    <a asp-area="Common" asp-controller="Home" asp-action="Dashboard" class="sidebar-logo"><span></span></a>
                    <a asp-area="Common" asp-controller="Home" asp-action="Dashboard" class="sidebar-logo-text">House<span>Rental</span></a>
                </div><!-- sidebar-header -->
                <div class="sidebar-body">
                    <nav class="nav-sidebar">
                        <a asp-area="Common" asp-controller="Home" asp-action="Dashboard" class="nav-link active"><i data-feather="package"></i><span>Dashboard</span></a>
                        <a asp-area="User" asp-controller="AccessoryItems" asp-action="Index" class="nav-link"><i data-feather="calendar"></i><span>Accessory Items</span></a>
                        <a asp-area="User" asp-controller="ApartmentBuilding" asp-action="Index" class="nav-link"><i data-feather="monitor"></i><span>Building</span></a>
                        <a asp-area="User" asp-controller="Apartment" asp-action="Index" class="nav-link"><i data-feather="shopping-bag"></i><span>Apartment</span></a>
                        <a asp-area="User" asp-controller="Tenant" asp-action="Index" class="nav-link"><i data-feather="file-text"></i><span>Tenant</span></a>
                        <a asp-area="User" asp-controller="ApartmentBooking" asp-action="Index" class="nav-link"><i data-feather="calendar"></i><span>Booking</span></a>
                        <a asp-controller="Reports" asp-action="Report" class="nav-link"><i data-feather="briefcase"></i><span>Tenants Reports</span></a>
                        <a asp-controller="Reports" asp-action="PaymentReport" class="nav-link"><i data-feather="briefcase"></i><span>Payment Reports</span></a>
                    </nav>

                    @if (User.IsInRole("Admin"))
                    {
                        <hr>
                        <nav class="nav-sidebar">
                            <a asp-area="Security" asp-controller="Users" asp-action="Index" class="nav-link"><i data-feather="users"></i><span>Manage Accounts</span></a>
                            <a asp-area="Security" asp-controller="Roles" asp-action="Index" class="nav-link"><i data-feather="package"></i><span>Manage Roles</span></a>
                        </nav>
                    }
                    <hr>
                    <nav class="nav-sidebar">
                        <a asp-area="Security" asp-controller="Account" asp-action="Singout" class="nav-link"><i data-feather="log-out"></i><span>Sing Out</span></a>
                    </nav>
                </div><!-- sidebar-body -->
                <div class="sidebar-footer">
                    <a href="" class="avatar online"><span class="avatar-initial">s</span></a>
                    <div class="avatar-body">
                        <div class="d-flex align-items-center justify-content-between">
                            <h6 class="text-uppercase">@User.Identity.Name</h6>
                            <a href="" class="footer-menu"><i class="ri-settings-4-line"></i></a>
                        </div>
                        <span>Superuser/Administrator</span>
                    </div><!-- avatar-body -->
                </div><!-- sidebar-footer -->
            </div><!-- sidebar -->
        }
    }
    <div class="content">
        <div class="content-header">
            <a id="contentMenu" href="#" class="content-menu d-none d-lg-flex"><i data-feather="menu"></i></a>
            <a id="mobileMenu" href="#" class="content-menu d-lg-none"><i data-feather="menu"></i></a>
        </div>
        <!-- content-header -->
        <div class="content-body">
            <!--<label class="content-label">Navigation Skins</label>-->
            @RenderBody()
        </div><!-- content-body -->
    </div><!-- content -->
    @RenderSection("Scripts", required: false)
</body>
</html>