HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Controllers/AccessoryItemsController.cs
using HouseRentalManagementSystem.IRepository;
using HouseRentalManagementSystem.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace HouseRentalManagementSystem.Areas.User.Controllers
{
    [Authorize]
    public class AccessoryItemsController : Controller
    {
        private readonly IApartmentFacilityRepository iApartmentFacilityRepository;
        private readonly IApartmentTypeRepository iApartmentTypeRepository;
        private readonly IBookingStatusRepository iBookingStatusRepository;
        private readonly IPaymentTypeRepository iPaymentTypeRepository;
        public AccessoryItemsController(IApartmentFacilityRepository _iApartmentFacilityRepository, IApartmentTypeRepository _iApartmentTypeRepository,IBookingStatusRepository _iBookingStatusRepository, IPaymentTypeRepository _iPaymentTypeRepository)
        {
            iApartmentFacilityRepository = _iApartmentFacilityRepository;
            iApartmentTypeRepository = _iApartmentTypeRepository;
            iBookingStatusRepository = _iBookingStatusRepository;
            iPaymentTypeRepository = _iPaymentTypeRepository;
        }
        int pageSize = 5;
        public IActionResult Index(int? facilityPage, int? typePage, int? bookingStatusPage, int? paymentTypePage)
        {
            dynamic dynamicItems = new ExpandoObject();
            int facilityPageNumber = (facilityPage ?? 1);
            int typePageNumber = (typePage ?? 1);
            int statusPageNumber = (bookingStatusPage ?? 1);
            int paymentTypePageNumber = (paymentTypePage ?? 1);
            dynamicItems.ApartmentFacilityViewModel = iApartmentFacilityRepository.GetAll().ToPagedList(facilityPageNumber, pageSize);
            dynamicItems.ApartmentTypeViewModel = iApartmentTypeRepository.GetAll().ToPagedList(typePageNumber, pageSize);
            dynamicItems.BookingStatusViewModel = iBookingStatusRepository.GetAll().ToPagedList(statusPageNumber, pageSize);
            dynamicItems.PaymentTypeViewModel = iPaymentTypeRepository.GetAll().ToPagedList(paymentTypePageNumber, pageSize);
            return View(dynamicItems);
        }


        [HttpPost]
        public IActionResult TypeCreate(ApartmentTypeViewModel obj, int? facilityPage, int? typePage, int? bookingStatusPage, int? paymentTypePage)
        {
            if (ModelState.IsValid)
            {
                iApartmentTypeRepository.Insert(obj);
            }
            dynamic dynamicItems = new ExpandoObject();
            int facilityPageNumber = (facilityPage ?? 1);
            int typePageNumber = (typePage ?? 1);
            int statusPageNumber = (bookingStatusPage ?? 1);
            int paymentTypePageNumber = (paymentTypePage ?? 1);
            dynamicItems.ApartmentFacilityViewModel = iApartmentFacilityRepository.GetAll().ToPagedList(facilityPageNumber, pageSize);
            dynamicItems.ApartmentTypeViewModel = iApartmentTypeRepository.GetAll().ToPagedList(typePageNumber, pageSize);
            dynamicItems.BookingStatusViewModel = iBookingStatusRepository.GetAll().ToPagedList(statusPageNumber, pageSize);
            dynamicItems.PaymentTypeViewModel = iPaymentTypeRepository.GetAll().ToPagedList(paymentTypePageNumber, pageSize);
            return PartialView("_ApartmentTypeList", dynamicItems);
        }
        [HttpGet]
        public PartialViewResult TypeEdit(int id)
        {
            ApartmentTypeViewModel obj = iApartmentTypeRepository.GetById(id);
            return PartialView("~/Areas/User/Views/AccessoryItems/_TypeEdit.cshtml", obj);
        }

        [HttpPost]
        public IActionResult TypeEdit(ApartmentTypeViewModel objModel)
        {
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.AptTypeCode > 0)
                {
                    iApartmentTypeRepository.Update(objModel);
                    result = true;
                }

            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Appartment type is not Edited"; 
                return RedirectToAction("Message", "Error", new { area = "" });
            }
        }
        public IActionResult TypeDelete(int id)
        {
            if (id>0)
            {
                iApartmentTypeRepository.Delete(id);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult BookingStatusCreate(BookingStatusViewModel obj, int? facilityPage, int? typePage, int? bookingStatusPage, int? paymentTypePage)
        {
            if (ModelState.IsValid)
            {
                iBookingStatusRepository.Insert(obj);
            }
            dynamic dynamicItems = new ExpandoObject();
            int facilityPageNumber = (facilityPage ?? 1);
            int typePageNumber = (typePage ?? 1);
            int statusPageNumber = (bookingStatusPage ?? 1);
            int paymentTypePageNumber = (paymentTypePage ?? 1);
            dynamicItems.ApartmentFacilityViewModel = iApartmentFacilityRepository.GetAll().ToPagedList(facilityPageNumber, pageSize);
            dynamicItems.ApartmentTypeViewModel = iApartmentTypeRepository.GetAll().ToPagedList(typePageNumber, pageSize);
            dynamicItems.BookingStatusViewModel = iBookingStatusRepository.GetAll().ToPagedList(statusPageNumber, pageSize);
            dynamicItems.PaymentTypeViewModel = iPaymentTypeRepository.GetAll().ToPagedList(paymentTypePageNumber, pageSize);
            return PartialView("_BookingStatusList", dynamicItems);
        }
        [HttpGet]
        public PartialViewResult FacilityEdit(int id)
        {
            ApartmentFacilityViewModel obj = iApartmentFacilityRepository.GetById(id);
            return PartialView("~/Areas/User/Views/AccessoryItems/_FacilityEdit.cshtml", obj);
        }

        [HttpPost]
        public IActionResult FacilityEdit(ApartmentFacilityViewModel objModel)
        {
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.FacilityCode > 0)
                {
                    iApartmentFacilityRepository.Update(objModel);
                    result = true;
                }

            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Appartment facility is not Edited"; 
                return RedirectToAction("Message", "Error", new { area = "" });
            }
        }
        public IActionResult FacilityDelete(int id)
        {
            if (id>0)
            {
                iApartmentFacilityRepository.Delete(id);
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult FacilityCreate(ApartmentFacilityViewModel obj, int? facilityPage, int? typePage, int? bookingStatusPage, int? paymentTypePage)
        {
            if (ModelState.IsValid)
            {
                iApartmentFacilityRepository.Insert(obj);
            }
            dynamic dynamicItems = new ExpandoObject();
            int facilityPageNumber = (facilityPage ?? 1);
            int typePageNumber = (typePage ?? 1);
            int statusPageNumber = (bookingStatusPage ?? 1);
            int paymentTypePageNumber = (paymentTypePage ?? 1);
            dynamicItems.ApartmentFacilityViewModel = iApartmentFacilityRepository.GetAll().ToPagedList(facilityPageNumber, pageSize);
            dynamicItems.ApartmentTypeViewModel = iApartmentTypeRepository.GetAll().ToPagedList(typePageNumber, pageSize);
            dynamicItems.BookingStatusViewModel = iBookingStatusRepository.GetAll().ToPagedList(statusPageNumber, pageSize);
            dynamicItems.PaymentTypeViewModel = iPaymentTypeRepository.GetAll().ToPagedList(paymentTypePageNumber, pageSize);
            return PartialView("_FacilityList", dynamicItems);
        }

        [HttpGet]
        public PartialViewResult StatusEdit(int id)
        {
            BookingStatusViewModel obj = iBookingStatusRepository.GetById(id);
            return PartialView("~/Areas/User/Views/AccessoryItems/_StatusEdit.cshtml", obj);
        }

        [HttpPost]
        public IActionResult StatusEdit(BookingStatusViewModel objModel)
        {
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.BookingStatusCode > 0)
                {
                    iBookingStatusRepository.Update(objModel);
                    result = true;
                }

            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Booking Status is not Edited"; 
                return RedirectToAction("Message", "Error", new { area = "" });
            }
        }
        public IActionResult StatusDelete(int id)
        {
            if (id > 0)
            {
                iBookingStatusRepository.Delete(id);
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult PaymentTypeCreate(PaymentTypeViewModel obj, int? facilityPage, int? typePage, int? bookingStatusPage, int? paymentTypePage)
        {
            if (ModelState.IsValid)
            {
                iPaymentTypeRepository.Insert(obj);
            }
            dynamic dynamicItems = new ExpandoObject();
            int facilityPageNumber = (facilityPage ?? 1);
            int typePageNumber = (typePage ?? 1);
            int statusPageNumber = (bookingStatusPage ?? 1);
            int paymentTypePageNumber = (paymentTypePage ?? 1);

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/AccessoryItems/Index.cshtml
@model dynamic
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-6 my-3">
        <div class="card">
            <div class="card-body">
                <form method="post" data-ajax="true"
                      data-ajax-update="#typeDivAjax"
                      data-ajax-loading="#TypeLoadingImage"
                      data-ajax-loading-duration="2000"
                      data-ajax-confirm="Are You Sure to Save this Data?"
                      data-ajax-complete="Clear"
                      asp-area="User" asp-action="TypeCreate" asp-controller="AccessoryItems" enctype="multipart/form-data">
                    <div class="pl-0">
                        <div><span class="sub_page_header d-inline-block">Apartment Type</span></div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="input-group">
                        <input type="text" id="AptTypeDescription" name="AptTypeDescription" class="form-control w-25" />
                        <span class="input-group-btn">
                            <button class="btn btn_sub_page">Add New Type</button>
                        </span>
                    </div>
                </form>
                <div class="col-md-12" id="TypeLoadingImage" style="display:none;">
                    <img src="~/images/app_images/loding.gif" width="100" height="100" />
                </div>
                <div class="my-5" id="typeDivAjax">
                    <partial name="~/Areas/User/Views/AccessoryItems/_ApartmentTypeList.cshtml" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 my-3">
        <div class="card">
            <div class="card-body">
                <form method="post" data-ajax="true"
                      data-ajax-update="#divAjax"
                      data-ajax-loading="#LoadingImage"
                      data-ajax-loading-duration="2000"
                      data-ajax-confirm="Are You Sure to Save this Data?"
                      data-ajax-complete="Clear"
                      asp-area="User" asp-action="FacilityCreate" asp-controller="AccessoryItems" enctype="multipart/form-data">
                    <div class="pl-0">
                        <div><span class="sub_page_header d-inline-block">Apartment Facilities</span></div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="input-group">
                        <input type="text" id="FacilityDescription" name="FacilityDescription" class="form-control w-25" />
                        <span class="input-group-btn">
                            <button class="btn btn_sub_page">Add New Facility</button>
                        </span>
                    </div>
                </form>
                <div class="col-md-12" id="LoadingImage" style="display:none;">
                    <img src="~/images/app_images/loding.gif" width="100" height="100" />
                </div>
                <div class="my-5" id="divAjax">
                    <partial name="~/Areas/User/Views/AccessoryItems/_FacilityList.cshtml" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 my-3">
        <div class="card">
            <div class="card-body">
                <form method="post" data-ajax="true"
                      data-ajax-update="#bookingStatusdivAjax"
                      data-ajax-loading="#bookingStatusLoadingImage"
                      data-ajax-loading-duration="2000"
                      data-ajax-confirm="Are You Sure to Save this Data?"
                      data-ajax-complete="Clear"
                      asp-area="User" asp-action="BookingStatusCreate" asp-controller="AccessoryItems" enctype="multipart/form-data">
                    <div class="pl-0">
                        <div><span class="sub_page_header d-inline-block">Booking Status</span></div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="input-group">
                        <input type="text" id="BookingStatusDescription" name="BookingStatusDescription" class="form-control w-25" disabled/>
                        <span class="input-group-btn">
                            <button class="btn btn_sub_page" disabled>Add New Status</button>
                        </span>
                    </div>
                </form>
                <div class="col-md-12" id="bookingStatusLoadingImage" style="display:none;">
                    <img src="~/images/app_images/loding.gif" width="100" height="100" />
                </div>
                <div class="my-5" id="bookingStatusdivAjax">
                    <partial name="~/Areas/User/Views/AccessoryItems/_BookingStatusList.cshtml" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 my-3">
        <div class="card">
            <div class="card-body">
                <form method="post" data-ajax="true"
                      data-ajax-update="#paymentTypedivAjax"
                      data-ajax-loading="#paymentTypeLoadingImage"
                      data-ajax-loading-duration="2000"
                      data-ajax-confirm="Are You Sure to Save this Data?"
                      data-ajax-complete="Clear"
                      asp-area="User" asp-action="PaymentTypeCreate" asp-controller="AccessoryItems" enctype="multipart/form-data">
                    <div class="pl-0">
                        <div><span class="sub_page_header d-inline-block">Payment Type</span></div>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="input-group">
                        <input type="text" id="PaymentTypeDetails" name="PaymentTypeDetails" class="form-control w-25" />
                        <span class="input-group-btn">
                            <button class="btn btn_sub_page">Add New Type</button>
                        </span>
                    </div>
                </form>
                <div class="col-md-12" id="paymentTypeLoadingImage" style="display:none;">
                    <img src="~/images/app_images/loding.gif" width="100" height="100" />
                </div>
                <div class="my-5" id="paymentTypedivAjax">
                    <partial name="~/Areas/User/Views/AccessoryItems/_PaymentTypeList.cshtml" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="TypeEditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Update Apartment Type</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="TypeEditDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/AccessoryItems/_TypeEdit.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="FacilityEditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Update Apartment Facility</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="FacilityEditDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/AccessoryItems/_FacilityEdit.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="StatusEditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Update Booking Status</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="StatusEditDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/AccessoryItems/_StatusEdit.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="PaymentTypeEditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Update Payment Type</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="PaymentTypeEditDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/AccessoryItems/_PaymentTypeEdit.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function Clear() {
        $(this).closest('form').find("input[type=text], textarea").val("");
    }

    function TypeUpdate(id) {
        $.ajax({
            url: "/User/AccessoryItems/TypeEdit?id=" + id,
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#TypeEditDiv').show();
                $('#TypeEditDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }

    function FacilityUpdate(id) {
        $.ajax({
            url: "/User/AccessoryItems/FacilityEdit?id=" + id,
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#FacilityEditDiv').show();
                $('#FacilityEditDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }

    function StatusUpdate(id) {
        $.ajax({
            url: "/User/AccessoryItems/StatusEdit?id=" + id,
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#StatusEditDiv').show();
                $('#StatusEditDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }
    function PaymentTypeUpdate(id) {
        $.ajax({
            url: "/User/AccessoryItems/PaymentTypeEdit?id=" + id,
            type: "GET",
            data: "",
            contentType: 'application/json; charset = utf-8',
            success: function (data) {
                $('#PaymentTypeEditDiv').show();
                $('#PaymentTypeEditDiv').html(data);
            },
            error: function () {
                alert("Error occured")
            }
        })
    }
</script>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/AccessoryItems/_ApartmentTypeList.cshtml
@model dynamic
<div>
    <table class="table table-bordered table-striped list_table">
        <thead>
            <tr>
                <th class="text-center">
                    ###
                </th>
                <th>
                    Apartment Type
                </th>
                <th class="text-center tbl_action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ApartmentTypeViewModel)
            {
                <tr>
                    <td class="text-center">
                        @item.SirialNumber
                    </td>
                    <td>
                        @item.AptTypeDescription
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <div class="dropdown">
                                <a class="btn_table dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" onclick='TypeUpdate(@item.AptTypeCode)' data-bs-toggle="modal" data-bs-target="#TypeEditModal">Edit</a></li>
                                    <li><a class="dropdown-item" asp-area="User" asp-controller="AccessoryItems" asp-action="TypeDelete" asp-route-id="@item.AptTypeCode" onclick="return confirm('Are you sure to delete?')">Delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div class="page_section">
        @Html.PagedListPager((IPagedList)Model.ApartmentTypeViewModel, typePage => Url.Action("Index", new { typePage = typePage }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navication" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
    </div>
</div>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/AccessoryItems/_BookingStatusList.cshtml
@model dynamic
<div>
    <table class="table table-bordered table-striped list_table">
        <thead>
            <tr>
                <th class="text-center">
                    ###
                </th>
                <th>
                    Booking Status
                </th>
                <th class="text-center tbl_action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BookingStatusViewModel)
            {
                <tr>
                    <td class="text-center">
                        @item.SirialNumber
                    </td>
                    <td>
                        @item.BookingStatusDescription
                    </td>
                    <td class="text-center">
                        @*<div class="btn-group">
                            <div class="dropdown">
                                <a class="btn_table dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" onclick='StatusUpdate(@item.BookingStatusCode)' data-bs-toggle="modal" data-bs-target="#StatusEditModal">Edit</a></li>
                                    <li><a class="dropdown-item" asp-area="User" asp-controller="AccessoryItems" asp-action="StatusDelete" asp-route-id="@item.BookingStatusCode" onclick="return confirm('Are you sure to delete?')">Delete</a></li>
                                </ul>
                            </div>
                        </div>*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div class="page_section">
        @Html.PagedListPager((IPagedList)Model.BookingStatusViewModel, bookingStatusPage => Url.Action("Index", new { bookingStatusPage = bookingStatusPage }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navication" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
    </div>
</div>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/AccessoryItems/_FacilityList.cshtml
@model dynamic
<div>
    <table class="table table-bordered table-striped list_table">
        <thead>
            <tr>
                <th class="text-center">
                    ###
                </th>
                <th>
                    Facility Description
                </th>
                <th class="text-center tbl_action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ApartmentFacilityViewModel)
            {
                <tr>
                    <td class="text-center">
                        @item.SirialNumber
                    </td>
                    <td>
                        @item.FacilityDescription
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <div class="dropdown">
                                <a class="btn_table dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" onclick='FacilityUpdate(@item.FacilityCode)' data-bs-toggle="modal" data-bs-target="#FacilityEditModal">Edit</a></li>
                                    <li><a class="dropdown-item" asp-area="User" asp-controller="AccessoryItems" asp-action="FacilityDelete" asp-route-id="@item.FacilityCode" onclick="return confirm('Are you sure to delete?')">Delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div class="page_section">
        @Html.PagedListPager((IPagedList)Model.ApartmentFacilityViewModel, facilityPage => Url.Action("Index", new { facilityPage = facilityPage }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navication" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
    </div>
</div>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/AccessoryItems/_PaymentTypeList.cshtml
@model dynamic
<div>
    <table class="table table-bordered table-striped list_table">
        <thead>
            <tr>
                <th class="text-center">
                    ###
                </th>
                <th>
                    Payment Type
                </th>
                <th class="text-center tbl_action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PaymentTypeViewModel)
            {
                <tr>
                    <td class="text-center">
                        @item.SirialNumber
                    </td>
                    <td>
                        @item.PaymentTypeDetails
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <div class="dropdown">
                                <a class="btn_table dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" onclick='PaymentTypeUpdate(@item.PaymentTypeId)' data-bs-toggle="modal" data-bs-target="#PaymentTypeEditModal">Edit</a></li>
                                    <li><a class="dropdown-item" asp-area="User" asp-controller="AccessoryItems" asp-action="PaymentTypeDelete" asp-route-id="@item.PaymentTypeId" onclick="return confirm('Are you sure to delete?')">Delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div class="page_section">
        @Html.PagedListPager((IPagedList)Model.ApartmentTypeViewModel, paymentTypePage => Url.Action("Index", new { paymentTypePage = paymentTypePage }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navication" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
    </div>
</div>